# basic operations

In [1]:
import numpy as np

In [ ]:
# Arithmatic operation on array is elementwise

In [6]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

In [7]:
a+b

array([11, 22, 33, 44])

In [8]:
a*b

array([ 10,  40,  90, 160])

In [9]:
a%b

array([0, 0, 0, 0])

In [10]:
a<30

array([ True,  True, False, False])

In [ ]:
# matrix multiplication

A = n * m
B = m * p
C = n * p

In [11]:
A = np.array([[1,2,3] , [4,5,6]])
B = np.array([[1,4],[2,5] , [3,5]])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
A.shape

(2, 3)

In [14]:
B

array([[1, 4],
       [2, 5],
       [3, 5]])

In [15]:
B.shape

(3, 2)

In [16]:
A.dot(B)

array([[14, 29],
       [32, 71]])

In [17]:
a = np.array([1,2,3,4,5])

In [18]:
a.shape

(5,)

In [ ]:
# Unary operations

In [21]:
a =np.array([10,20,30,40])

In [22]:
# sum

a.sum()

100

In [23]:
# min

a.min()

10

In [24]:
# max

a.max()

40

In [26]:
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [27]:
# give sum of all the rows
"""
axis = 1 --> rowsie
axis = 0 --> column wise

"""
a.sum()

276

In [28]:
a.sum(axis = 1)

array([ 15,  51,  87, 123])

In [29]:
# give sum of all the col

a.sum(axis = 0)


array([36, 40, 44, 48, 52, 56])

In [30]:
a.min(axis = 1)

array([ 0,  6, 12, 18])

In [31]:
a.max(axis=1)

array([ 5, 11, 17, 23])

In [32]:
a.min(axis = 0)

array([0, 1, 2, 3, 4, 5])

In [33]:
a.max(axis = 0)

array([18, 19, 20, 21, 22, 23])

# Universal Functions

In [34]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

In [35]:
np.add(a,b)

array([11, 22, 33, 44])

In [37]:
np.subtract(a,b)

array([ 9, 18, 27, 36])

In [38]:
np.multiply(a,b)

array([ 10,  40,  90, 160])

In [39]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [41]:
np.square(b)

array([ 1,  4,  9, 16])

In [42]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [43]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [45]:
a = np.arange(24).reshape(6,4)

In [46]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
mean = a.mean()

In [48]:
mean

11.5

In [51]:
np.median(a)

11.5

In [52]:
np.std(a)

6.922186552431729

In [53]:
np.var(a)

47.916666666666664

In [54]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
np.mean(a , axis = 0)

array([10., 11., 12., 13.])

In [56]:
np.mean(a , axis = 1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [ ]:
['afsan' , 'hairni' , 'abc' , 'xyz']

In [57]:
a.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [58]:
np.mode(a)

AttributeError: module 'numpy' has no attribute 'mode'

In [59]:
# indexing and slicing in numpy arrays

In [60]:
a = np.arange(4)

In [61]:
a

array([0, 1, 2, 3])

In [62]:
# indexing
a[-1]

3

In [63]:
a = np.arange(28).reshape(7,4)

In [64]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [65]:
a[1][1]

5

In [66]:
a[3][2]

14

In [68]:
# slicing
a[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [75]:
a = np.arange(28).reshape(7,4)

In [76]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [77]:
a[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
a[1:4,::2]

array([[ 4,  6],
       [ 8, 10],
       [12, 14]])

In [78]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [79]:
a[2::2,::-1]

array([[11, 10,  9,  8],
       [19, 18, 17, 16],
       [27, 26, 25, 24]])

In [73]:
a = 'afsaan'
a[::2]

'asa'

In [81]:
a[::-1,::]

array([[24, 25, 26, 27],
       [20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [83]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [82]:
a[::-3 , ::3]

array([[24, 27],
       [12, 15],
       [ 0,  3]])

In [85]:
# iteraing

a = np.array([1,2,3,4,5])

In [86]:
for i in a:
    print(i)

1
2
3
4
5


In [87]:
a = np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [88]:
for i in a:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


In [89]:
for i in a:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [90]:
for i in a.flatten():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
# splitting of an array

In [91]:
array = np.arange(12)

In [92]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.split(array , int/list)

"""
int --> number of elemnts should be divisble by the int
"""

In [94]:
np.split(array,5)

ValueError: array split does not result in an equal division

In [95]:
array = np.arange(12)*2

In [96]:
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [97]:

"""
0-0
0-3 -> 0 2 4 6
4-6 -> 8 10 12
7-9 -> 14,16,18
10+ -> 20,22

"""
np.split(array , [0,4,7,10])

[array([], dtype=int64),
 array([0, 2, 4, 6]),
 array([ 8, 10, 12]),
 array([14, 16, 18]),
 array([20, 22])]

In [98]:
np.split(array , [2,4,7,9,11])
"""
0-2
2-4
4-7
7-9
9-11
11+
"""

np.split(array , [2,4,7,9,11])

[array([0, 2]),
 array([4, 6]),
 array([ 8, 10, 12]),
 array([14, 16]),
 array([18, 20]),
 array([22])]

In [105]:
array = np.arange(24).reshape(4,6)

In [106]:
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [107]:
"""
axis - 1 - column wise
axis - 0 - row wise
"""

np.split(array,3,axis = 1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [109]:
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [110]:
np.split(array,2,axis = 0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [116]:
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [118]:

"""
how many splits - 5
0-2
2-4
4-6
6-8
8+
"""
np.split(array,[2,4,6,8],axis = 1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]]),
 array([], shape=(4, 0), dtype=int64),
 array([], shape=(4, 0), dtype=int64)]

In [111]:
np.split(array,[2,4,6,8],axis = 0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([], shape=(0, 6), dtype=int64),
 array([], shape=(0, 6), dtype=int64),
 array([], shape=(0, 6), dtype=int64)]

In [112]:
np.hsplit(array,[2,4,6,8])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]]),
 array([], shape=(4, 0), dtype=int64),
 array([], shape=(4, 0), dtype=int64)]

In [113]:
np.vsplit(array,[2,4,6,8])

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([], shape=(0, 6), dtype=int64),
 array([], shape=(0, 6), dtype=int64),
 array([], shape=(0, 6), dtype=int64)]

In [ ]:
vector
copy and view
pandas