In [ ]:
Numpy - Numerical python

- python package used for computatio and processing of single dimesion and mul;ti dim array
- numpy is extended module of python mainely wriiten in c
- fast and optimised
- provides fast and efficeient way to compute and handle the large number of data
- numpy can only contan homegenous data

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

# create a numpy array using

1. list
2. tuple
3. methods in np

In [5]:
# 1. list

a = [1,2,3,4,5,6]

array = np.array(a)
print(array , type(array))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [6]:
# 1. tuple

a = (1,2,3,4,5,6)

array = np.array(a)
print(array , type(array))


[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [ ]:
0 - saclar
[1,2,3,4,5] - vector - 1d
2d - row,col
3d - row,col,dept
4d
5d

In [7]:
# check the size of an array - number of elements
array.size

6

In [8]:
# check the shape of an array - shape ---> tuple
array.shape

(6,)

In [9]:
# check the dim
array.ndim

1

In [10]:
a = [[1,2],[3,4],[5,6]]

array = np.array(a)
print(array , type(array))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [11]:
array.size

6

In [12]:
array.shape

(3, 2)

In [14]:
array.ndim

2

In [16]:
# arange

np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [17]:
# linspace
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [18]:
3.20408163 - 3.02040816

0.18367347

In [19]:
7.79591837 - 7.6122449

0.18367346999999956

In [21]:
# zeros - all the ele will be zero

np.zeros(5)

array([0, 0, 0, 0, 0])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
# zeros_like

a = [[1,2],[3,4],[5,6]]

array = np.array(a)
print(array , type(array))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [24]:
np.zeros_like(array)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [25]:
# ones

np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones_like(array)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [28]:
# eye  - identity matrix
"""
sqaure - n*n
dig are 1 and rest of the ele is 0
"""

np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [30]:
a = [[1,2,3] , [4,5,6] , [5,6,9] , [11,12,13]]
data = np.array(a)

In [31]:
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  9],
       [11, 12, 13]])

In [33]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros_like(data)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
np.zeros((4,3))

array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0

In [42]:
# random

data = np.random.rand(4,6)

In [43]:
data.ndim

2

In [44]:
data

array([[0.44525007, 0.30820119, 0.72674206, 0.2178298 , 0.75428663,
        0.66611924],
       [0.67332572, 0.59763286, 0.96082442, 0.23884814, 0.64953195,
        0.29977611],
       [0.06481954, 0.89388479, 0.70711645, 0.83055425, 0.01981183,
        0.96757084],
       [0.65445572, 0.09867178, 0.28146383, 0.46940355, 0.44210113,
        0.85710763]])

In [46]:
# Reshaping

a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
6

In [ ]:
1d - 2d

2d - 2*3 m 3*2, 6*1 , 1*6

In [47]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [49]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [50]:
a.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [62]:
names = np.array(['afsan' , 'Gautham' , 'abinash', 'aditya' , 'akshatha' , 'akanksha' , 'akshansh'])

In [60]:
names

array(['afsan', 'Gautham', 'abinash', 'aditya', 'akshatha', 'akanksha',
       'akshansh', 'aaaaaaaaaaa'], dtype='<U11')

In [ ]:
<U8 ---> all the string <= unistring of len 8

In [63]:
names.reshape(1,7)

array([['afsan', 'Gautham', 'abinash', 'aditya', 'akshatha', 'akanksha',
        'akshansh']], dtype='<U8')

In [64]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [65]:
a.reshape(3,1,2)

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [67]:
# infer

array = np.arange(18).reshape(6,3)

In [68]:
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [69]:
array.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [70]:
array = np.arange(2000).reshape(2,2,5,100)

In [72]:
# convert array into 2 dim where number rows should be 20
array.reshape(20,-1)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [1700, 1701, 1702, ..., 1797, 1798, 1799],
       [1800, 1801, 1802, ..., 1897, 1898, 1899],
       [1900, 1901, 1902, ..., 1997, 1998, 1999]])

In [74]:
array.reshape(4,2,-1).shape

(4, 2, 250)

In [ ]:
In case if 3d to be done it will be likearray.reshape(2,-1,-1)? Right

In [75]:
array.reshape(4,-1,-1).shape

ValueError: can only specify one unknown dimension

In [ ]:
# transpose

matrix - n*m
t matrix - m*n

In [89]:
data =  np.arange(100).reshape(2,5,10)

In [90]:
data

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [91]:
data.shape

(2, 5, 10)

In [92]:
data.T.shape

(10, 5, 2)

In [ ]:
# ravel / flatten - any dim - 1 dim

In [93]:
data

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [95]:
data.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [96]:
data.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])